/akame/roboclaw_driver:
  ros__parameters:
    roboclaw_port: "/dev/serial/by-id/usb-Basicmicro_Inc._USB_Roboclaw_Solo_30A-if00"
    baud: 34800
    cmd_vel_in: /roboclaw_vel
    cmd_pos_in: /roboclaw_pos
    calibrate_in: /roboclaw_calibrate
    address: 0x80
    pos_homing_hz: 50

/akame/go_m8010_6_driver:
  ros__parameters:
    cmd_in: cmd_vel
    left_motor: "/dev/ttyUSB0"
    right_motor: "/dev/ttyUSB1"
    left_motor_id: 0
    right_motor_id: 1
    position_damping: 0.005
    velocity_damping: 0.05
    wheel_radius: 1.0
    vehicle_width: 0.076

/akame/drum_driver:
  ros__parameters:
    cmd_in: "/drum"
    motor: "/dev/ttyUSB2"
    motor_id: 2
    position_damping: 0.005
    velocity_damping: 0.01
