/vive_tracker/vive_tracker:
  ros__parameters:
    topic: "odom"
    frame_id: "tracker_link"
    visual_topic: "visual"
    visualization: true
    poll_delay: 25
    zero_on_init: true
    zero_topic: "vive/zero"
