/akame/openvr_tracker:
  ros__parameters:
    topic: "openvr_tracker/odom"
    frame_id: vive_link
    visual_topic: openvr_tracker/visual
    visualization: false
    poll_delay: 50

/akame/vive_to_odom:
  ros__parameters:
    frame_publish_interval: 0.005
    pos_in: "openvr_tracker/odom"
    pos_out: "odom"
